### ISSUE TITLE
Request open source code based on CONCH score filtering

### ISSUE THREAD

**Issue by lsnls** [DeepMicroscopy/QuiltCleaner#2]
Hello, thank you very much for your outstanding work!

I'm unable to locate the code to filter based on the CONCH score in the repository. Would it be possible for you to open source it?

I'm looking forward to hearing from you! Thank you!

**Comment by maubreville** [comment]
Hey there! 

Sure. I added my notebook that I used for it:

https://github.com/DeepMicroscopy/QuiltCleaner/blob/main/CONCH_Calculation_FullQUILT.ipynb

Best,

Marc

**Comment by lsnls** [comment]
Thank you very much for the timely reply and code update!
